# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := TD8_ARENA

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

TD8_ARENA: 
	@echo "==== Building TD8_ARENA ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f TD8_ARENA.make

clean:
	@${MAKE} --no-print-directory -C . -f TD8_ARENA.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TD8_ARENA"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
