# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := TD8_ARENA test_3d test_calib test_controller test_3d_controller test_ship_control_3d test_game test_chessboard

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

TD8_ARENA: 
	@echo "==== Building TD8_ARENA ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f TD8_ARENA.make

test_3d: 
	@echo "==== Building test_3d ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_3d.make

test_calib: 
	@echo "==== Building test_calib ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_calib.make

test_controller: 
	@echo "==== Building test_controller ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_controller.make

test_3d_controller: 
	@echo "==== Building test_3d_controller ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_3d_controller.make

test_ship_control_3d: 
	@echo "==== Building test_ship_control_3d ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_ship_control_3d.make

test_game: 
	@echo "==== Building test_game ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_game.make

test_chessboard: 
	@echo "==== Building test_chessboard ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test_chessboard.make

clean:
	@${MAKE} --no-print-directory -C . -f TD8_ARENA.make clean
	@${MAKE} --no-print-directory -C . -f test_3d.make clean
	@${MAKE} --no-print-directory -C . -f test_calib.make clean
	@${MAKE} --no-print-directory -C . -f test_controller.make clean
	@${MAKE} --no-print-directory -C . -f test_3d_controller.make clean
	@${MAKE} --no-print-directory -C . -f test_ship_control_3d.make clean
	@${MAKE} --no-print-directory -C . -f test_game.make clean
	@${MAKE} --no-print-directory -C . -f test_chessboard.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TD8_ARENA"
	@echo "   test_3d"
	@echo "   test_calib"
	@echo "   test_controller"
	@echo "   test_3d_controller"
	@echo "   test_ship_control_3d"
	@echo "   test_game"
	@echo "   test_chessboard"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
